/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eb9a94c5-8134-4938-a0d2-378f87f00225",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_AmZ1IjCZQ",
    "aws_user_pools_web_client_id": "v2q5fga1qe7dqjm0gjnlta9fq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://f6k4kg6zvvhefh6apg75hohjfq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-up7yegbgyzahnojsxvgzt4vmxu",
    "aws_user_files_s3_bucket": "avatarappcf8b03e953a84aa6948d323105d0b66b214200-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
